// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4dLsFFNi3tJzoxq5aNyqoqRjLI_pJGh0',
    appId: '1:853669298380:web:71f244d13553da3be9c269',
    messagingSenderId: '853669298380',
    projectId: 'vacaynest-1343c',
    authDomain: 'vacaynest-1343c.firebaseapp.com',
    storageBucket: 'vacaynest-1343c.firebasestorage.app',
    measurementId: 'G-H1MC7HZTSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwRtv1waAWTo5v7RVnNgWBZg59-MLYcE',
    appId: '1:853669298380:android:dc22e697250d13e4e9c269',
    messagingSenderId: '853669298380',
    projectId: 'vacaynest-1343c',
    storageBucket: 'vacaynest-1343c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtu1N7tGvHVjhKZr6xapJsc0XWXv45VE',
    appId: '1:853669298380:ios:2057d9e5058ad0e6e9c269',
    messagingSenderId: '853669298380',
    projectId: 'vacaynest-1343c',
    storageBucket: 'vacaynest-1343c.firebasestorage.app',
    iosBundleId: 'com.example.vacaynestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKtu1N7tGvHVjhKZr6xapJsc0XWXv45VE',
    appId: '1:853669298380:ios:2057d9e5058ad0e6e9c269',
    messagingSenderId: '853669298380',
    projectId: 'vacaynest-1343c',
    storageBucket: 'vacaynest-1343c.firebasestorage.app',
    iosBundleId: 'com.example.vacaynestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4dLsFFNi3tJzoxq5aNyqoqRjLI_pJGh0',
    appId: '1:853669298380:web:924ef8250625fd51e9c269',
    messagingSenderId: '853669298380',
    projectId: 'vacaynest-1343c',
    authDomain: 'vacaynest-1343c.firebaseapp.com',
    storageBucket: 'vacaynest-1343c.firebasestorage.app',
    measurementId: 'G-PQP1KBLCZN',
  );
}
